### ISSUE TITLE
侧边栏的链接修改顺序页面刷新后无效

### ISSUE THREAD

**Issue by tgly307** [zhuowenli/githuber#14]
侧边栏的链接有时需要调整顺序，但是打开新页面或者刷新后仍然按照添加顺序显示，调整效果未生效。

**Comment by tgly307** [comment]
看了一下代码，拖拽以后触发的`updateBookmarks`事件只是把结果保存到了store的bookmarks中，并没有存储到storage里，所以刷新重新读取就失效了。感觉应该是这个原因。

**Comment by tgly307** [comment]
#18 提交了PR

**Comment by zhuowenli** [comment]
感谢反馈，已合并代码。下个版本生效~
