### ISSUE TITLE
建议和反馈

### ISSUE THREAD

**Issue by ShaoXinSen** [zhuowenli/githuber#15]
能不能再做个优化?
就是打开新标签页的时候, 可以看到整个页面都是白色的,是否可以考虑下左侧书签等本地部分的数据页面直接展示, github内容部分刷新.

还有个问题, 左边书签栏, 退出chrome后丢失之前排序

**Comment by zhuowenli** [comment]
排序会在 #18 解决。白屏问题是因为用了 vue 来渲染，之前也有很多网友反馈这个，预计会在 2.0 解决该问题~~
