### ISSUE TITLE
内容部分一直显示空白页

### ISSUE THREAD

**Issue by chongrui** [zhuowenli/githuber#24]
从昨天（9月26日）起，内容部分一直显示空白页，如下图所示：
<img width="1084" alt="screen shot 2018-09-27 at 10 39 30" src="https://user-images.githubusercontent.com/17204669/46164125-fe4e3080-c241-11e8-9c67-a6772e164c0a.png">
测试浏览器：Chrome 69.0.3497.100  IP: 207.126.240.13 
请问能否帮助解决，谢谢！

**Comment by zhuowenli** [comment]
麻烦按 `Cmd + Shift + J`（macOS）或者 `F12`（Windows） 打开控制台，先看看有没有什么报错提示。

然后顺便切换到 Application Tab，找到对应的 Local Storage，选中 `{"lang":"","since":"daily"}` 这一项后，把内容复制给我我看看。

**Comment by chongrui** [comment]
@zhuowenli 不好意思没有及时回复， report这个issue后一天，插件恢复正常工作了。我现在怀疑可能是我自己的网络环境设置问题。如果将来有问题我会及时反馈的，谢谢您的帮助！
