### ISSUE TITLE
可以提供程序语言的多选么

### ISSUE THREAD

**Issue by SHERlocked93** [zhuowenli/githuber#25]
您好，您的插件用起来非常好用，感谢你的工作

界面上的语言可以提供多选功能么，比如说我比较关心css、html、js的，那么我就选择这几个语言，而不是只能选择一个语言来回手动切换

![image](https://user-images.githubusercontent.com/24636076/46582841-f717f580-ca7f-11e8-89a5-c94667c10fdf.png)

继续加油~

**Comment by zhuowenli** [comment]
这个建议挺好的，我有空安排搞下，也欢迎提 PR。
