### ISSUE TITLE
mac下显示问题

### ISSUE THREAD

**Issue by wcflmy** [zhuowenli/githuber#33]
mac版本：macOS High Sierra
chrome版本：71.0.3578.98

在我的mac下显示有点诡异，如下：

![image](https://user-images.githubusercontent.com/13165590/49940951-17e74600-ff1c-11e8-92d5-2a7c61f028e9.png)

缩小至80%后正常。

**Comment by zhuowenli** [comment]
![image](https://user-images.githubusercontent.com/9620783/49946884-d7db8f80-ff2a-11e8-84e0-457118bfe040.png)
跟你同一个版本，貌似没问题。感觉像浏览器缩放 125% 了，你按 `Cmd + 0` 试试。😂

**Comment by wcflmy** [comment]
还真是...[尴尬].png
