### ISSUE TITLE
关于e30e项目导致的收藏栏消失问题.

### ISSUE THREAD

**Issue by Teloi** [zhuowenli/githuber#34]
一个有趣的bug,持续了一周左右的时间.
关于e30e项目来源介绍:https://linuxwit.ch/blog/2018/12/e98e/
![image](https://user-images.githubusercontent.com/16536457/49983192-237a5180-ff9c-11e8-9f87-b42a836a0715.png)
附:很喜欢这个插件!

**Comment by zhuowenli** [comment]
新版已解决

**Comment by Teloi** [comment]
![image](https://user-images.githubusercontent.com/16536457/49996128-1d4e9a00-ffc9-11e8-86ff-ef39d9293128.png)

**Comment by Teloi** [comment]
或许
min-width: calc(100% - 300px);

**Comment by zhuowenli** [comment]
哈哈哈大意了
