### ISSUE TITLE
不能点击

### ISSUE THREAD

**Issue by ZhangBo1191** [zhuowenli/githuber#36]
不能点击最常访问、不能点击项目，没有反应。但右键是正常的…………

**Comment by ZhangBo1191** [comment]
已经重装过GITHUBER了

**Comment by ZhangBo1191** [comment]
还是不行

**Comment by ZhangBo1191** [comment]
Chrome 版本 73.0.3679.0
GITHUBER 版本 1.4.2

**Comment by zhuowenli** [comment]
麻烦打开浏览器控制台（Mac：Cmd + Option + J，Windows：F12），看看有没有报错信息。如果有的话，提供下截图。

**Comment by ZhangBo1191** [comment]
![image](https://user-images.githubusercontent.com/36790218/52033249-474f2200-255f-11e9-97b3-8f4b48022cca.png)

**Comment by zhuowenli** [comment]
点击后会有报错么？

**Comment by ZhangBo1191** [comment]
没有

**Comment by zhuowenli** [comment]
好吧，我先升级下浏览器看看能不能复现。

**Comment by ZhangBo1191** [comment]
链接: https://pan.baidu.com/s/1HS4DBYgU146qZJ2OizcUIg 提取码: tq4v 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by ZhangBo1191** [comment]
视频

**Comment by zhuowenli** [comment]
还有麻烦帮忙在新窗口打开这个地址： chrome://extensions/?id=janmcneaglgklfljjcpihkkomeghljnf
截个图看看下面这个权限信息是否正常~

![image](https://user-images.githubusercontent.com/9620783/52034017-0573ab00-2562-11e9-8dd6-5eae9f65fccf.png)

**Comment by ZhangBo1191** [comment]
![bandicam 2019-01-31 14-14-59-730](https://user-images.githubusercontent.com/36790218/52034180-abbfb080-2562-11e9-8dc1-487e9a2d0602.jpg)

**Comment by ZhangBo1191** [comment]
好像是可以点的……但是点的方式特别诡异

**Comment by zhuowenli** [comment]
我在 macOS 上装了 72.0.3626.81 beta 64 以及 74.0.3690.0 canary 64 都没有这个问题。感觉是我调用 Chrome API 的 tabs 接口时浏览器出了啥问题。。。
