### ISSUE TITLE
mac 手势无法使用

### ISSUE THREAD

**Issue by StringKe** [zhuowenli/githuber#44]
mac 有个左右滑动前进后退的功能
![image](https://user-images.githubusercontent.com/31089228/58463113-d105a980-8165-11e9-81ba-fa3f92668f2b.png)
![image](https://user-images.githubusercontent.com/31089228/58463162-e8dd2d80-8165-11e9-81a7-6238903da5ee.png)
这个区域内功能无效

**Comment by zhuowenli** [comment]
我在这边做了自定义滚动，然后把系统默认滚动事件给拦截了。目前暂时无法开放出来。
