### ISSUE TITLE
trending页面结构变了，获取结果失效

### ISSUE THREAD

**Issue by tgly307** [zhuowenli/githuber#47]
github的trending页面结构改成了语义化标签，repo信息放在了article标签内，原有的获取方式失效了

**Comment by yxxhero** [comment]
我也遇到这个问题了 什么时候可以修复

**Comment by tgly307** [comment]
pr已经提交了，看作者什么时候有空合并了发布新版本吧

**Comment by zhuowenli** [comment]
应用市场已发布
