### ISSUE TITLE
为什么最近不能看每日每周最热了，每月的可以，刷新也没用

### ISSUE THREAD

**Issue by k36666** [zhuowenli/githuber#53]

**Comment by zhuowenli** [comment]
麻烦打开浏览器控制台（Mac：Cmd + Option + J，Windows：F12），然后刷新页面看看有没有报错信息。如果有的话，提供下截图。

**Comment by k36666** [comment]
错误截图如下






在 2019-08-19 13:37:55，"卓文理" <notifications@github.com> 写道：


麻烦打开浏览器控制台（Mac：Cmd + Option + J，Windows：F12），然后刷新页面看看有没有报错信息。如果有的话，提供下截图。

**Comment by zhuowenli** [comment]
截图貌似加载不出来

**Comment by k36666** [comment]
这次加在附件里了，请您看下






在 2019-08-19 17:17:44，"卓文理" <notifications@github.com> 写道：


截图貌似加载不出来

**Comment by zhuowenli** [comment]
额，你恐怕得来 GitHub 网站上面评论了，发邮件我无法接收到图片跟附件。
https://github.com/zhuowenli/githuber/issues/53

**Comment by k36666** [comment]
![image](https://user-images.githubusercontent.com/48466140/63346520-bbc8a180-c387-11e9-86a9-8e08561fd70b.png)

**Comment by zhuowenli** [comment]
刚刚发布了个新版本，有时间升级下试试还会不会报 CORS 的错误～
