### ISSUE TITLE
显示不出具体star数量, 全部是0

### ISSUE THREAD

**Issue by 1314cc** [zhuowenli/githuber#57]
![image](https://user-images.githubusercontent.com/5126487/64747107-9838e700-d540-11e9-8eb3-8d0c1e18aa7c.png)

版本: 
![image](https://user-images.githubusercontent.com/5126487/64747172-c0284a80-d540-11e9-9bfe-31b24b961a1e.png)

**Comment by zhuowenli** [comment]
收到

**Comment by 1012598167** [comment]
和我这边完全一致的问题

**Comment by zhuowenli** [comment]
已经发布了新版本了
