### ISSUE TITLE
无法显示具体star数量, 全部是0

### ISSUE THREAD

**Issue by HSantu** [zhuowenli/githuber#67]
如同 #57 一样的问题，版本是 Chrome 应用商店下载的最新版，附图下
![image](https://user-images.githubusercontent.com/23703054/88151417-3f90ab00-cc35-11ea-8e7f-71c3218cbd29.png)

![image](https://user-images.githubusercontent.com/23703054/88151423-43bcc880-cc35-11ea-831c-4683abd71f7b.png)

**Comment by zhuowenli** [comment]
已经重新提审了
