### ISSUE TITLE
显示网络异常

### ISSUE THREAD

**Issue by Jack-lss** [zhuowenli/githuber#75]
无论内外，大屏幕都显示网络异常，搜索栏可以搜索，侧边栏链接可以打开

**Comment by yxxhero** [comment]
我也是  你咋解决的

**Comment by Jack-lss** [comment]
我试过重装，还是不行，估计托管平台崩了
Application Error
The error occurred in the hosted application
The deployment has been disabled
451: DEPLOYMENT_DISABLED
Code: DEPLOYMENT_DISABLED
ID: hkg1::wrkvk-1601893198530-e9f7031efbfa

**Comment by zhuowenli** [comment]
https://github.com/huchenme/github-trending-api/issues/130 托管平台服务有问题，我这边先找台服务器自己部署下。

**Comment by zhuowenli** [comment]
#76 该问题已解决

**Comment by zzhzero** [comment]
https://gtrend.flwha.com/repositories?language=&since=daily 502
