### ISSUE TITLE
网络异常

### ISSUE THREAD

**Issue by teaper** [zhuowenli/githuber#82]
![2021-01-03_16-56.png](http://ww1.sinaimg.cn/large/006kWbIogy1gmam0r8d60j31h10j976u.jpg)

**Comment by woodpenker** [comment]
似乎是这个地址挂了: `https://gtrend.flwha.com/repositories`

**Comment by lorentz-wu** [comment]
就是这个地址挂了，啥时候修好啊　https://gtrend.flwha.com/repositories

**Comment by zhuowenli** [comment]
done
