### ISSUE TITLE
blocked by CORS policy

### ISSUE THREAD

**Issue by JounQin** [zhuowenli/githuber#85]
![image](https://user-images.githubusercontent.com/8336744/109454839-1f10b500-7a90-11eb-9a04-60a5934019dd.png)

**Comment by zhuowenli** [comment]
done

**Comment by JounQin** [comment]
@zhuowenli Again 😂

https://gtrend.flwha.com/repositories?language=&since=daily

502 Bad Gateway

![image](https://user-images.githubusercontent.com/8336744/113650834-77585980-96c3-11eb-820a-dbc58c0c63e1.png)
