### ISSUE TITLE
恢复数据时无法选择备份文件

### ISSUE THREAD

**Issue by CrazyBunQnQ** [zhuowenli/githuber#86]
Chrome 版本 89.0.4389.90（正式版本） (x86_64)

![image](https://user-images.githubusercontent.com/17765748/111930055-fa3db980-8af2-11eb-9e10-c88354e1b8b8.png)

**Comment by zhuowenli** [comment]
点下选项，然后格式设为所有文件；或者把文件后缀改成 .githuber 即可。
